<?php

/**
 * @file
 * LocalGov Elections Reporting module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function localgov_elections_theme($existing, $type, $theme, $path): mixed {
  return [
    'area_result' => [
      'variables' => [
        'chart' => NULL,
        'result' => NULL,
        'analysis' => NULL,
      ],
    ],
    'election_menu' => [
      'variables' => [
        'links' => NULL,
      ],
    ],
    'localgov_elections_results_heading' => [
      'variables' => [
        'election_type' => '',
      ],
    ],
    'views_view_table__localgov_election_results__summary_table' => [
      'base hook' => 'views_view_table',
    ],
    'election_timeline_table_row' => [
      'variables' => [
        'time' => NULL,
        'area' => NULL,
        'area_url' => NULL,
        'seats' => 0,
        'candidates' => [],
      ],
      'template' => 'election-timeline-table-row',
    ],
    'views_view_unformatted__localgov_election_results_timeline' => [
      'variables' => [
        'rows' => [],
        'title' => NULL,
      ],
      'template' => 'election-timeline-table',
    ],
    'analysis_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_modules_installed().
 */
function localgov_elections_modules_installed($modules, $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  $services = in_array('localgov_services_navigation', $modules, TRUE);
  if ($services) {
    \Drupal::service('config.installer')->installOptionalConfig(NULL, [
      'config' => 'field.storage.node.localgov_services_parent',
    ]);
    _localgov_elections_optional_fields_settings($services);
  }
}

/**
 * Set form settings for optional services fields on installation.
 *
 * @param bool $services
 *   If localgov_services is (being) installed.
 */
function _localgov_elections_optional_fields_settings($services): void {
  $properties = [
    'targetEntityType' => 'node',
    'bundle' => 'localgov_election',
  ];
  if ($form_displays = \Drupal::entityTypeManager()->getStorage('entity_form_display')->loadByProperties($properties)) {
    foreach ($form_displays as $form_display) {
      assert($form_display instanceof EntityFormDisplayInterface);
      if ($services && !$form_display->getComponent('localgov_services_parent')) {
        $form_display->setComponent('localgov_services_parent', [
          'type' => 'entity_reference_autocomplete',
          'region' => 'content',
          'settings' => [
            'match_operator' => 'CONTAINS',
            'size' => '60',
            'placeholder' => '',
            'match_limit' => 10,
          ],
          'weight' => -1,
        ])->save();
        if (
          ($field_groups = $form_display->getThirdPartySettings('field_group')) &&
          ($group = $field_groups['group_description'] ?? FALSE)
        ) {
          $group['children'][] = 'localgov_services_parent';
          $form_display->setThirdPartySetting('field_group', 'group_description', $group)
            ->save();
        }
      }
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function localgov_elections_entity_presave(EntityInterface $entity): void {
  if ($entity->getEntityTypeId() === 'node' && $entity->getType() === 'localgov_area_vote') {

    $finalised = $entity->get('localgov_election_votes_final')->value;
    $uncontested_area = $entity->get('localgov_election_no_contest')->value;

    if ($finalised === 1 || $uncontested_area === 1) {
      /** @var \Drupal\localgov_elections\Service\WinnerCalculator $calculator */
      $calculator = \Drupal::service('localgov_elections.winner_calculator');
      $winners = $calculator->calculateWinners($entity);

      $entity->set('localgov_election_winner', $winners);
    }
    else {
      // If vote is not finalised, clear previous winners.
      if ($original = $entity->original) {
        if ($original->get('localgov_election_votes_final')->value == 1) {
          $entity->set('localgov_election_winner', []);
        }
      }
    }

    // Remove completely empty candidates from seats.
    if ($entity->hasField('localgov_election_seats')) {
      foreach ($entity->get('localgov_election_seats') as $seat_item) {
        $seat = $seat_item->entity;
        if ($seat && $seat->bundle() === 'localgov_area_seat') {
          $candidates = $seat->get('localgov_candidate_uncontested');
          $to_delete = [];

          foreach ($candidates as $delta => $candidate_item) {
            $candidate = $candidate_item->entity;
            if ($candidate) {
              // Check all candidate fields for content.
              $has_any_data = FALSE;
              $excluded_fields = [
                'id',
                'uuid',
                'type',
                'langcode',
                'status',
                'created',
                'changed',
                'parent_id',
                'parent_type',
                'parent_field_name',
              ];
              foreach ($candidate->getFields() as $field) {
                if (!$field->isEmpty() && !in_array($field->getName(), $excluded_fields)) {
                  $has_any_data = TRUE;
                  break;
                }
              }

              // If completely empty, delete it.
              if (!$has_any_data) {
                $to_delete[] = $delta;
              }
            }
          }

          // Remove and delete.
          foreach (array_reverse($to_delete) as $delta) {
            $candidate = $candidates[$delta]->entity;
            $candidates->removeItem($delta);
            $candidate->delete();
          }
        }
      }
    }
  }

  // Prevent creating multiple revisions for candidate paragraphs.
  if ($entity->getEntityTypeId() === 'paragraph' && $entity->getType() === 'localgov_election_candidate') {
    $entity->setNewRevision(FALSE);
  }
}

/**
 * Implements hook_node_insert().
 *
 * Create default seats when area vote is created.
 */
function localgov_elections_node_insert(NodeInterface $node) {
  if ($node->bundle() !== 'localgov_area_vote') {
    return;
  }

  // Ensure the reference to parent election exists.
  if ($node->hasField('localgov_election') && !$node->get('localgov_election')->isEmpty()) {
    $parent = $node->get('localgov_election')->entity;
    if ($parent instanceof NodeInterface && $parent->hasField('localgov_election_seat_count')) {
      $seat_count = (int) $parent->get('localgov_election_seat_count')->value;

      // Only proceed if no seats already exist.
      if (!$node->get('localgov_election_seats')->isEmpty()) {
        return;
      }

      // Base name for seats.
      $area_name = $node->get('localgov_election_area_name')->value ?? 'Seat';
      // If the area is marked as uncontested, set all seats to uncontested.
      $area_uncontested = $node->get('localgov_election_no_contest')->value ?? 0;

      $paragraph_storage = \Drupal::entityTypeManager()->getStorage('paragraph');
      $seat_paragraphs = [];

      // Always create at least 1 seat, more if parent requires it.
      for ($i = 1; $i <= $seat_count; $i++) {
        $seat_label = $seat_count > 1 ? $area_name . ' ' . $i : $area_name;

        $seat_paragraph = $paragraph_storage->create([
          'type' => 'localgov_area_seat',
          'localgov_seat' => $seat_label,
          'localgov_seat_not_contested' => $area_uncontested,
        ]);
        $seat_paragraph->save();

        $seat_paragraphs[] = $seat_paragraph;
      }

      // Attach them to the node's reference field.
      foreach ($seat_paragraphs as $seat_paragraph) {
        $node->get('localgov_election_seats')->appendItem($seat_paragraph);
      }

      // Save the node again with attached paragraphs.
      $node->save();
    }
  }
}

/**
 * Implements hook_entity_predelete().
 */
function localgov_elections_entity_predelete(EntityInterface $entity): void {
  // Triggered just before an Election node is deleted.
  if ($entity->getEntityTypeId() == 'node' && $entity->getType() == 'localgov_election') {
    $election_id = $entity->id();
    $election_title = $entity->getTitle();
    $deleted = 0;

    // Delete all Division Vote entities referencing this election.
    $areas_query = \Drupal::entityTypeManager()->getStorage('node')->getQuery();
    $areas_query->condition('type', 'localgov_area_vote');
    $areas_query->condition('status', 1);
    $areas_query->condition('localgov_election', $election_id);
    $areas_query->accessCheck(FALSE);
    $areas = $areas_query->execute();

    if ($areas) {
      $areas = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($areas);
      foreach ($areas as $area) {
        try {
          $area->delete();
          $deleted++;
        }
        catch (EntityStorageException $exception) {
          \Drupal::logger('localgov_election')->error("Could not delete area with id " . $area->id());
        }
      }
    }

    \Drupal::logger('localgov_election')
      ->notice("Election " . $election_title . " (ID " . $election_id . ") was deleted. " . $deleted . " Division Votes deleted");
    \Drupal::messenger()->addStatus($deleted . ' Division Votes deleted from system');
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function localgov_elections_path_alias_insert(EntityInterface $entity): void {
  $path = $entity->getPath();
  $url = Url::fromUserInput($path);
  $params = $url->getRouteParameters();

  if (is_array($params) && array_key_exists('node', $params)) {
    if ($node = Node::load($params['node'])) {
      if ($node->bundle() === "localgov_election") {
        $canonical_route = '/' . $node->toUrl()->getInternalPath();
        if ($path === $canonical_route) {
          /** @var \Drupal\localgov_elections\Service\ElectionAliasManager $alias_manager */
          $alias_manager = \Drupal::service('localgov_elections.alias_manager');
          $alias_manager->generateElectionAliases($node);
        }
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function localgov_elections_path_alias_update(EntityInterface $entity): void {
  /** @var \Drupal\path_alias\Entity\PathAlias $original_entity */
  $original_entity = $entity->original;

  if ($entity->getAlias() !== $original_entity->getAlias()) {
    $path = $entity->getPath();
    $url = Url::fromUserInput($path);
    $params = $url->getRouteParameters();

    if (is_array($params) && array_key_exists('node', $params)) {
      if ($node = Node::load($params['node'])) {
        if ($node->bundle() === "localgov_election") {
          $canonical_route = '/' . $node->toUrl()->getInternalPath();
          if ($path === $canonical_route) {
            /** @var \Drupal\localgov_elections\Service\ElectionAliasManager $alias_manager */
            $alias_manager = \Drupal::service('localgov_elections.alias_manager');
            $alias_manager->deleteElectionAliases($node);
            $alias_manager->generateElectionAliases($node);
          }
        }
      }
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for add form.
 */
function localgov_elections_form_node_localgov_area_vote_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\localgov_elections\Form\AreaVoteFormHelper $form_helper */
  $form_helper = \Drupal::service('localgov_elections.area_vote_form_helper');
  $form_helper->configureForm($form, $form_state);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for edit form.
 */
function localgov_elections_form_node_localgov_area_vote_edit_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  /** @var \Drupal\localgov_elections\Form\AreaVoteFormHelper $form_helper */
  $form_helper = \Drupal::service('localgov_elections.area_vote_form_helper');
  $form_helper->configureForm($form, $form_state);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function localgov_elections_form_taxonomy_term_localgov_party_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if (isset($form["name"]["widget"][0]['value'])) {
    $form["name"]["widget"][0]['value']["#description"] = t("The party name. Do not enter brackets in the party name.");
  }
}

/**
 * Implements hook_views_data_alter().
 */
function localgov_elections_views_data_alter(array &$data): void {
  $data['node']['ward_majority'] = [
    'title' => t('Area majority'),
    'field' => [
      'title' => t('Area majority'),
      'help' => t('Calculates the difference between number of votes of first and second results in an electoral area.'),
      'id' => 'ward_majority',
    ],
  ];
  $data['node']['area_party'] = [
    'title' => t('Area winning party'),
    'field' => [
      'title' => t('Area winning party'),
      'help' => t('Winning party in an electoral area for an election.'),
      'id' => 'area_party',
    ],
  ];
  $data['node']['election_turnout'] = [
    'title' => t('Election turnout'),
    'field' => [
      'title' => t('Election turnout'),
      'help' => t('Sums all votes cast with all candidates in election plus all spoiled votes.'),
      'id' => 'election_turnout',
    ],
  ];
  $data['node']['election_timeline'] = [
    'title' => t('Election timeline'),
    'field' => [
      'title' => t('Election timeline'),
      'help' => t('Gathers timeline data for an area.'),
      'id' => 'election_timeline',
    ],
  ];
  $data['node']['election_majority'] = [
    'title' => t('Election majority'),
    'field' => [
      'title' => t('Election majority'),
      'help' => t('Counts number of seats in election, divides by 2 and adds 1 to calculate majority.'),
      'id' => 'election_majority',
    ],
  ];
  $data['node']['area_seats_count'] = [
    'title' => t('Area seats count'),
    'field' => [
      'title' => t('Area seats count'),
      'help' => t('Counts the number of seats in an electoral area.'),
      'id' => 'area_seats_count',
    ],
  ];
  $data['paragraph']['winner_tie_indicator'] = [
    'title' => t('Winner tie indicator'),
    'group' => t('Paragraph'),
    'field' => [
      'title' => t('Winner tie indicator'),
      'help' => t('Displays " (tie winner)" if the winner won on a tie.'),
      'id' => 'winner_tie_indicator',
    ],
  ];
  $data['taxonomy_term_data']['election_share'] = [
    'title' => t('Percentage of election share'),
    'field' => [
      'title' => t('Percentage of election share'),
      'help' => t('List percentage of election share for each party in a specific election.'),
      'id' => 'election_share',
    ],
  ];
  $data['taxonomy_term_data']['election_seats_party'] = [
    'title' => t('Election seat wins'),
    'field' => [
      'title' => t('Election seat wins'),
      'help' => t('Sums all seats won by party in this election.'),
      'id' => 'election_seats_party',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'standard',
    ],
  ];
  $data['views']['area_election_results_heading'] = [
    'title' => t('Election results heading'),
    'help' => t('Sets dynamic heading depending on election type.'),
    'area' => [
      'id' => 'localgov_elections_results_heading',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function localgov_elections_views_pre_render(ViewExecutable $view): void {
  $view_storage = $view->storage;
  $dependencies = $view_storage ? $view_storage->get('dependencies') : [];
  $enforced_modules = $dependencies['enforced']['module'] ?? [];

  if (in_array('localgov_elections', $enforced_modules, TRUE)) {
    $view->element['#attached']['library'][] = 'localgov_elections/election';
  }

  if ($view->id() === 'localgov_electoral_candidates') {
    $view->element['#attached']['library'][] = 'localgov_elections/electoral_candidates_view';
  }

  if ($view->id() === 'localgov_election_results_timeline') {
    $view->element['#attached']['drupalSettings']['localgov_elections']['parties'] = _localgov_elections_party_colours();
    $view->element['#attached']['library'][] = 'localgov_elections/results_timeline';
    $view->element['#attached']['library'][] = 'localgov_elections/party_colours';
  }

  if ($view->id() === 'localgov_election_results') {
    if ($view->getDisplay()->display['id'] === 'summary_table') {
      $view->element['#attached']['library'][] = 'localgov_elections/party_colours';
    }
  }

  if ($view->id() === 'localgov_election_results_vote') {
    $view->element['#attached']['drupalSettings']['localgov_elections']['parties'] = _localgov_elections_party_colours();
    $view->element['#attached']['library'][] = 'localgov_elections/party_colours';
  }
}

/**
 * Implements hook_views_post_render().
 */
function localgov_elections_views_post_render(ViewExecutable $view, array &$output, CachePluginBase $cache): void {
  if ($view->id() === 'localgov_election_results_via_parties') {
    // Remove rows from rendered output where party is not standing in election.
    if (!isset($output["#rows"]["block_party_results__election_seats_party_0"]["#data"])) {
      return;
    }
    $rows = $output["#rows"]["block_party_results__election_seats_party_0"]["#data"];
    if (!is_array($rows)) {
      return;
    }
    $idx = 0;
    $removed = 0;
    foreach ($rows as $row) {
      if (!isset($row)) {
        array_splice($output["#rows"]["block_party_results__election_seats_party_0"]["#data"], $idx - $removed, 1);
        array_splice($output["#rows"]["xaxis"]["#labels"], $idx - $removed, 1);
        if (isset($output["#rows"]["block_party_results__election_seats_party_0"]["#mapped_data"])) {
          array_splice($output["#rows"]["block_party_results__election_seats_party_0"]["#mapped_data"], $idx - $removed, 1);
        }
        $removed++;
      }
      $idx++;
    }
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function localgov_elections_preprocess_views_view__localgov_election_electoral_map(&$variables) {
  $view = $variables['view'];

  /** @var \Drupal\localgov_elections\Service\MapDataProvider $map_data_provider */
  $map_data_provider = \Drupal::service('localgov_elections.map_data_provider');
  $map_data = $map_data_provider->prepareMapData($view);

  if (!empty($map_data)) {
    $variables['#attached']['drupalSettings']['electoralMapData'] = $map_data;
    $variables['#attached']['library'][] = 'localgov_elections/electoral-map';
  }
}

/**
 * Implements hook_chart_alter().
 */
function localgov_elections_chart_alter(array &$element, $chart_id): void {
  $element['#attached']['library'][] = 'localgov_elections/chartjs_overrides';
  $element['#attached']['drupalSettings']['localgov_elections']['parties'] = _localgov_elections_party_colours();
}

/**
 * Implements hook_chart_definition_CHART_ID_alter().
 */
function localgov_elections_chart_definition_localgov_election_results_via_parties_block_party_results_alter(array &$definition, array $element, $chart_id): void {
  $definition['yAxis'][0]['allowDecimals'] = FALSE;
  if (!empty($definition['series'][0]['data'])) {
    foreach ($definition['series'][0]['data'] as &$entry) {
      if ($entry == NULL) {
        $entry = 0;
      }
    }
  }

  if ($majority = _localgov_elections_calc_majority()) {
    $max = 0;
    if (!empty($definition['series'][0]['data'])) {
      $max = max($definition['series'][0]['data']);
    }

    if ($majority > $max) {
      $max = $majority;
    }

    // Allow hiding of plot line.
    if ($election = \Drupal::request()->get('node')) {
      if ($election->hasField("localgov_election_majority")) {
        $display_majority_details = $election->get("localgov_election_majority")?->value;
      }
      else {
        $display_majority_details = FALSE;
      }
      if ($display_majority_details) {
        $definition['yAxis'][0]['plotLines'] = [
          [
            'color' => '#8c8a8a',
            'width' => 6,
            'value' => $majority,
            'dashStyle' => 'LongDash',
          ],
        ];
      }
      $definition['yAxis'][0]['max'] = $max + 4;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_elections_preprocess_node(&$variables): void {
  $node = $variables['elements']['#node'];

  if ($node->bundle() == 'localgov_area_vote') {
    $finalised = $node->get('localgov_election_votes_final')->value;
    $not_contested = $node->get('localgov_election_no_contest')->value;

    if ($finalised == 1) {
      if ($not_contested) {
        $variables['content']['results'] = [
          '#children' => t('This seat was not contested.'),
        ];
      }
      else {
        $block_manager = \Drupal::service('plugin.manager.block');
        $plugin_block = $block_manager->createInstance('analysis_block', []);
        $analysis = $plugin_block->build();

        // Add the cache tags/contexts.
        \Drupal::service('renderer')->addCacheableDependency($analysis, $plugin_block);

        $variables['content']['results'] = [
          '#theme' => 'area_result',
          '#chart' => [
            '#type' => 'view',
            '#name' => 'localgov_election_area_results',
            '#arguments' => [$node->id()],
          ],
          '#result' => [
            '#type' => 'view',
            '#name' => 'localgov_election_area_results',
            '#display_id' => 'block_area_results_table',
            '#arguments' => [$node->id()],
          ],
          '#analysis' => $analysis,
          '#attached' => ['library' => ['localgov_elections/party_colours']],
        ];
      }
    }
    else {
      $variables['content']['results'] = [
        '#children' => t('No results have been declared yet.'),
      ];
    }
  }
  elseif ($node->bundle() == 'localgov_election') {
    if ($node->hasField('localgov_election_majority')) {
      $display_majority = $node->get("localgov_election_majority")?->value;
    }
    else {
      $display_majority = FALSE;
    }

    $variables['content']['results_fieldset'] = [
      '#type' => 'container',
      '#prefix' => '<div class="area-summary"> <div class="area-summary__header" ><h2>' . t("Seats won") . '</h2></div>',
      '#suffix' => '</div>',
    ];

    $variables['content']['results_fieldset']['sub_heading'] = [
      '#type' => 'container',
      '#prefix' => '<div class="area-summary__subheading">',
      '#suffix' => '</div>',
    ];

    $variables['content']['results_fieldset']['sub_heading']['election_results_electorate'] = [
      '#type' => 'view',
      '#name' => 'localgov_election_results',
      '#display_id' => 'block_electorate',
      '#arguments' => [$node->id()],
    ];

    $variables['content']['results_fieldset']['sub_heading']['election_results_turnout'] = [
      '#type' => 'view',
      '#name' => 'localgov_election_results',
      '#display_id' => 'block_area_winners',
      '#arguments' => [$node->id()],
    ];

    $variables['content']['results_fieldset']['election_results_by_party'] = [
      '#type' => 'view',
      '#name' => 'localgov_election_results_via_parties',
      '#display_id' => 'block_party_results',
      '#arguments' => [$node->id()],
    ];

    if ($display_majority) {
      $variables['content']['results_fieldset']['election_results_majority'] = [
        '#type' => 'view',
        '#name' => 'localgov_election_results',
        '#display_id' => 'block_majority',
        '#arguments' => [$node->id()],
      ];
    }

    $variables['content']['election_results_summary_table'] = [
      '#type' => 'view',
      '#name' => 'localgov_election_results',
      '#display_id' => 'summary_table',
      '#arguments' => [$node->id()],
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_elections_preprocess_election_menu(&$variables): void {
  $attributes = new Attribute();
  $attributes->setAttribute('id', 'election-menu');
  $variables['attributes'] = $attributes;

  $current = \Drupal::routeMatch()->getRouteName();
  foreach ($variables['links'] as $link) {
    /** @var \Drupal\Core\Link $url */
    $url = $link['link'];
    if ($url->getUrl()->getRouteName() == $current) {
      if ($node = \Drupal::routeMatch()->getParameter('node')) {
        if ($node instanceof NodeInterface) {
          if ($node->bundle() == 'localgov_area_vote') {
            return;
          }
        }
      }
      $link['attributes']->addClass('active');
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_elections_preprocess_block(&$variables): void {
  if ($variables['base_plugin_id'] == 'localgov_elections_electionmenu') {
    $variables['attributes']['class'][] = 'election-menu-block';
  }

  // Set the page title to be the name of the area.
  $node = \Drupal::request()->attributes->get('node');
  if ($node && $node instanceof NodeInterface) {
    if ($node->bundle() == 'localgov_area_vote') {
      if ($variables['base_plugin_id'] == 'localgov_page_header_block') {
        $variables['content'][0]['#title'] = $node->get('localgov_election_area_name')->value;
      }
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function localgov_elections_menu_local_tasks_alter(&$data, $route_name): void {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface) {
    $type = $node->getType();
    if ($type != 'localgov_election') {
      // Hide election-specific tabs from non-election nodes.
      unset($data['tabs'][0]['views_view:view.localgov_election_results_timeline.page_timeline']);
      unset($data['tabs'][0]['views_view:view.localgov_election_results_vote.page_vote_share']);
      unset($data['tabs'][0]['views_view:view.localgov_electoral_candidates.page_candidates']);
      unset($data['tabs'][0]['views_view:view.localgov_election_electoral_map.page_map']);
    }
    else {
      $appropriate_fetch_routes = [
        "entity.node.canonical",
        "entity.node.edit_form",
        "entity.node.version_history",
        "entity.node.delete_form",
        "entity.node.preview_link_generate",
      ];

      // Add the "add area" button to the local tasks if user has permission.
      $can_add_areas = \Drupal::currentUser()->hasPermission('can fetch boundaries');
      if ($can_add_areas && in_array($route_name, $appropriate_fetch_routes, TRUE)) {
        $data['tabs'][0]['boundary_fetch'] = [
          '#theme' => 'menu_local_task',
          '#weight' => 100,
          '#link' => [
            'title' => t('Add areas'),
            'url' => Url::fromRoute('localgov_elections.boundary_fetch', ['node' => $node->id()]),
          ],
        ];
      }
    }
  }

  if ($route_name === 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');

    if ($node instanceof NodeInterface && $node->bundle() !== 'localgov_election') {
      // Remove duplicate tab if not localgov_election.
      unset($data['tabs'][0]['localgov_elections.election_duplicate_tab']);
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function localgov_elections_page_attachments(array &$attachments): void {
  $route = \Drupal::routeMatch();

  if ($node = $route->getParameter('node')) {
    if ($node != NULL && $node instanceof NodeInterface) {
      if ($node->bundle() === 'localgov_election') {
        $attachments['#attached']['library'][] = 'localgov_elections/election';
      }
      elseif ($node->bundle() === 'localgov_area_vote') {
        $attachments['#attached']['library'][] = 'localgov_elections/election';
        $attachments['#attached']['library'][] = 'localgov_elections/area_results';
      }
    }
  }
}

/**
 * Calculate number of seats needed for a majority.
 */
function _localgov_elections_calc_majority(): ?int {
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!$node instanceof NodeInterface) {
    return NULL;
  }

  /** @var \Drupal\localgov_elections\Service\MajorityCalculator $calculator */
  $calculator = \Drupal::service('localgov_elections.majority_calculator');
  return $calculator->calculateMajority($node);
}

/**
 * Get party colours and metadata.
 */
function _localgov_elections_party_colours(): array {
  $results = [];
  $terms = \Drupal::entityTypeManager()
    ->getStorage('taxonomy_term')
    ->loadByProperties(['vid' => 'localgov_party']);

  if ($terms && is_array($terms)) {
    foreach ($terms as $term) {
      $colour = $term->get('localgov_election_party_colour')->color ?? NULL;
      $abbr = $term->get('localgov_election_abbreviation')->value ?? NULL;

      if ($colour && $abbr) {
        $abbr = strtolower($abbr);

        $results[$abbr] = [
          'text-colour' => $term->get('localgov_election_text_colour')->color ?? NULL,
          'colour' => $colour,
          'full_name' => $term->getName(),
          'abbr' => $abbr,
        ];
      }
    }
  }

  return $results;
}

/**
 * Implements hook_entity_update().
 */
function localgov_elections_entity_update(EntityInterface $entity): void {
  if ($entity->getEntityTypeId() === 'node' && $entity->getType() === 'localgov_area_vote') {
    // Clean up empty uncontested candidates from seats.
    if ($entity->hasField('localgov_election_seats')) {
      $seats = $entity->get('localgov_election_seats')->referencedEntities();

      foreach ($seats as $seat) {
        if ($seat->bundle() === 'localgov_area_seat') {
          $seat_not_contested = $seat->get('localgov_seat_not_contested')->value;
          $candidate = $seat->get('localgov_candidate_uncontested')->entity;

          if ($candidate) {
            $should_delete = !$seat_not_contested || $candidate->get('localgov_election_party')->isEmpty();

            if ($should_delete) {
              $candidate->delete();
            }
          }
        }
      }
    }
  }
}
