localgov_elections_configurable_provider.boundary_source.export:
  path: '/admin/structure/boundary-source/{boundary_source}/export'
  defaults:
    _controller: '\Drupal\localgov_elections_configurable_provider\Controller\BoundarySourceExportController::export'
    _title_callback: '\Drupal\localgov_elections_configurable_provider\Controller\BoundarySourceExportController::exportTitle'
  requirements:
    _permission: 'administer boundary_source'
  options:
    parameters:
      boundary_source:
        type: entity:boundary_source

localgov_elections_configurable_provider.boundary_source.import:
  path: '/admin/structure/boundary-source/import'
  defaults:
    _form: '\Drupal\localgov_elections_configurable_provider\Form\BoundarySourceImportForm'
    _title: 'Import Boundary Source'
  requirements:
    _permission: 'administer boundary_source'
