charts_default_settings:
  library: highcharts
  type: bar
  display:
    title: ''
    title_position: out
    data_labels: false
    data_markers: false
    legend_position: right
    background: ''
    three_dimensional: 0
    colors:
      - '#d8810f'
      - '#0d233a'
      - '#8bbc21'
      - '#910000'
      - '#1aadce'
      - '#492970'
      - '#f28f43'
      - '#77a1e5'
      - '#c42525'
      - '#a6c96a'
    polar: 0
    tooltips: true
    dimensions:
      width: ''
      width_units: '%'
      height: ''
      height_units: ''
    gauge:
      max: '100'
      min: '0'
      green_from: '85'
      green_to: '100'
      yellow_from: '50'
      yellow_to: '85'
      red_from: '0'
      red_to: '50'
  xaxis:
    title: ''
    labels_rotation: '0'
  yaxis:
    title: ''
    min: ''
    max: ''
    prefix: ''
    suffix: ''
    decimal_count: ''
    labels_rotation: '0'
  highcharts_settings:
    legend:
      layout: vertical
      background_color: ''
      border_width: '0'
      item_style:
        color: ''
        overflow: ''
      shadow: 0
    exporting_library: 0
advanced:
  debug: false
  requirements:
    cdn: true
