charts_default_settings:
  library: chartjs
  type: bar
  display:
    title: ''
    title_position: out
    subtitle: ''
    data_labels: false
    data_markers: false
    legend_position: right
    background: ''
    three_dimensional: 0
    colors:
      - '#d8810f'
      - '#0d233a'
      - '#8bbc21'
      - '#910000'
      - '#1aadce'
      - '#492970'
      - '#f28f43'
      - '#77a1e5'
      - '#c42525'
      - '#a6c96a'
    polar: 0
    tooltips: true
    dimensions:
      width: ''
      width_units: '%'
      height: ''
      height_units: ''
    gauge:
      max: '100'
      min: '0'
      green_from: '85'
      green_to: '100'
      yellow_from: '50'
      yellow_to: '85'
      red_from: '0'
      red_to: '50'
    color_changer: false
  xaxis:
    title: ''
    labels_rotation: '0'
  yaxis:
    title: ''
    min: ''
    max: ''
    prefix: ''
    suffix: ''
    decimal_count: ''
    labels_rotation: '0'
  library_config:
    xaxis:
      autoskip: false
      horizontal_axis_title_align: start
    yaxis:
      vertical_axis_title_align: start
advanced:
  debug: false
  requirements:
    cdn: true
dependencies:
  module:
    - charts_chartjs
